ScrumBoardApp/Models/Board/BoardModel.cs
using System;
using System.Collections.Generic;
using ScrumBoardApp.Models.Column;

namespace ScrumBoardApp.Models
{
    public class BoardModel : BaseEntityModel
    {
        public Guid UserId { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateUpdated { get; set; }

        public ICollection<ColumnModel> BoardColumns { get; set; }


    }
}

ScrumBoardApp/Controllers/Board/BoardController.cs
using AutoMapper;
using BLL.Models;
using BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Identity;
using ScrumBoardApp.Models;
using ScrumBoardApp.Models.Column;
using DAL.Entities;
using System.Xml.Linq;

namespace ScrumBoardApp.Controllers.Board
{
    public class BoardController : Controller
    {

        private UserManager<DAL.Entities.User> _currentUser;

        public BoardController(UserManager<DAL.Entities.User> userManager)
        {
            _currentUser = userManager;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var id = Guid.Parse(_currentUser.GetUserId(User)); // Get user id:


            List<BoardModel> list = default;

            using (var db = new BllBoardService())
                list = Mapper.Map<List<BoardModel>>(db.GetBoards().Where(b => b.UserId.Equals(id))).OrderBy(x=>x.Name).ToList();

            return View(list);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Delete(Guid Id)
        {
            //Guid id = Guid.Parse(Id);
            using (var db = new BllBoardService())
                db.RemoveBoard(Id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Details()
        {
            return RedirectToAction("Index","Column");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Update(BoardModel update)
        {

            update.DateUpdated = DateTime.Now;
            update.UserId = Guid.Parse(_currentUser.GetUserId(User));

            using (var db = new BllBoardService())
                db.UpdateBoard(Mapper.Map<BoardBL>(update));

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public ActionResult AddBoard()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddBoard(string name, Guid userId)
        {
            
            if (User.Identity.IsAuthenticated)
            {
                string g = User.Identity.Name;

                bool IsAdmin = User.IsInRole("Admin");
                bool IsUser = User.IsInRole("User");
                bool IsMoserator = User.IsInRole("Moderator");

                var id = _currentUser.GetUserId(User); // Get user id:
            }

            BoardModel board = new BoardModel()
            {
                Id = Guid.NewGuid(),
                Name = name,
                UserId = Guid.Parse(_currentUser.GetUserId(User)), // Get user id:
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            using (var db = new BllBoardService())
            {
                db.AddBoard(Mapper.Map<BoardBL>(board));
            }

            return RedirectToAction("Index");
        }
    }
}

ScrumBoardApp/Controllers/BoardController.cs
using AutoMapper;
using BLL.Models;
using BLL.Services;
using ScrumBoardApp.Models;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ScrumBoardApp.Controllers
{
    public class BoardController : Controller
    {

        // GET: RegistrationController
        [HttpGet]
        public ActionResult AddBoard()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBoard(string name, Guid userId)
        {
            BoardModel board = new BoardModel()
            {
                Name = name,
                UserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            using (var db = new BllBoardService())
            {
                db.AddBoard(Mapper.Map<BoardBL>(board));
            }

            return Redirect("~/Home/Success");
        }
    }
}

ScrumBoardApp/Controllers/User/BoardController.cs
using AutoMapper;
using BLL.Models;
using BLL.Services;
using ScrumBoardApp.Models;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ScrumBoardApp.Controllers.User
{
    public class BoardController : Controller
    {
        private IConfiguration configuration { get; }

        public BoardController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        // GET: RegistrationController
        [HttpGet]
        public ActionResult AddBoard()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBoard(string name, Guid userId)
        {
            BoardModel board = new BoardModel()
            {
                Name = name,
                UserId = userId,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now
            };

            using (var db = new BllBoardService(configuration))
            {
                db.AddBoard(Mapper.Map<BoardBL>(board));
            }

            return Redirect("~/Home/Success");
        }
    }
}

ScrumBoardApp/Views/Board/AddBoard.cshtml
@model ScrumBoardApp.Models.BoardModel
@{
    ViewData["Title"] = "AddBoard";
}

<link rel="stylesheet" href="~/css/fields.css" media="screen" type="text/css" />

<div class="row justify-content-center align-items-center" >
    <div class="col-md-4">
        <h4>AddBoard</h4>
        <form asp-action="AddBoard" asp-controller="Board">
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control"/>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Board" class="btn btn-primary"/>
            </div>

        </form>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

ScrumBoardApp/Views/Board/Details.cshtml
@{
    ViewData["Title"] = "Calculate";
}

    <h2>Details</h2>
<table class="table table-sm table">
    <tr>
        <td>Id</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Pice</td>
        <td>@Model.Price</td>
    </tr>
    <tr>
        <td>Description</td>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <td>Quantity</td>
        <td>@Model.Quantity</td>
    </tr>
    <tr>
        <td>ClientBindingModel Group</td>
        <td>@Model.Group</td>
    </tr>
</table>

@*<table>
    <tr class="bg-primary">
        <td>Id</td>
        <td>@Model.Id</td>
    </tr>
    <tr class="bg-success">
        <td>Название</td>
        <td>@Model.Name</td>
    </tr>
    <tr class="bg-warning">
        <td>Цена</td>
        <td>@Model.Price</td>
    </tr>
    <tr class="bg-danger">
        <td>Description</td>
        <td>@Model.Description</td>
    </tr>
    <tr class="bg-info">
        <td>Quantity</td>
        <td>@Model.Quantity</td>
    </tr>
    <tr class="bg-info">
        <td>Grop</td>
        <td>@Model.Group</td>
    </tr>
</table>*@

ScrumBoardApp/Views/Board/Index.cshtml
@model List<ScrumBoardApp.Models.BoardModel>
@{
    ViewData["Title"] = "Index";
}


<h2>List of my boards: </h2>
    <table class="table">

        <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Date created</th>
            <th scope="col">Date last updated</th>
            <th scope="col">...</th>
        </tr>
        </thead>

        @foreach (var item in Model)
        {
                    <tbody>
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.DateCreated</td>
                        <td>@item.DateUpdated</td>
                        <td>
                            <a asp-action="Details" asp-controller="Board" class="btn btn-outline-primary" tabindex="-1" role="button" aria-disabled="true">Select</a>
                            <a asp-action="Update" asp-controller="Board" asp-route-id="@item.Id" class="btn btn-outline-info" tabindex="-1" role="button" aria-disabled="true">Update</a>
                            <a asp-action="Delete" asp-controller="Board" asp-route-id="@item.Id" class="btn btn-outline-danger" tabindex="-1" role="button" aria-disabled="true">Delete</a>
                        </td>
                    </tr>
                    </tbody>
        }
        <tr><td><a asp-action="AddBoard" asp-controller="Board"  class="btn btn-outline-success" tabindex="-1" role="button" aria-disabled="true">Add</a></td></tr>
    </table>


@if (Model.Count != 0)
{
            <h2>
                Total Position: @Model.Count
            </h2>
}
else
{

    <div class="alert alert-warning" role="alert">
        Ups...Boards not found...List board is empty :( 

    </div>

    <p>  </p>

    <table>
        <tr>
            <a asp-action="AddBoard" asp-controller="Board" class="btn btn-success" tabindex="-1" role="button" aria-disabled="true">Create first board</a>
            or           
            <a asp-action="Index" asp-controller="Home" class="btn btn-secondary" tabindex="-1" role="button" aria-disabled="true">Back to Home page</a>
        </tr>
    </table>
}

ScrumBoardApp/Views/Board/Update.cshtml
@model ScrumBoardApp.Models.BoardModel
@{
    ViewData["Title"] = "Update";
}

<link rel="stylesheet" href="~/css/fields.css" media="screen" type="text/css" />

<div class="row justify-content-center align-items-center" >
    <div class="col-md-4">

        <h1>Update</h1>

        <form asp-action="Update" asp-controller="Board">

            <div class="form-group">
                <label asp-for="Name" class="control-label">Input new Name</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Board" class="btn btn-primary"/>
            </div>

        </form>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>